Code/bad_walden_stadtwerke/pom.xml

pom configuration update

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/InitialSignUpControllerStep0.java

Added language support for selecting language on initial sign up screen to enhance user experience.

fix: Add sign up language label to InitialSignUpControllerStep0

---

.idea/.gitignore
.idea/ATIT2.iml
.idea/compiler.xml
.idea/encodings.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/Customer.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/ValidateBillingAddress.java
Code/bad_walden_stadtwerke/src/test/java/ValidateBillingAddressTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/ValidateBillingAddressTest.java

Unit Tests laufen, jedes Feld wird validiert. Implementierung dann noch notwendig. Customer Klasse kann danach erzeugt werden. Return auch so, dass man sieht welches Feld Fehler wirft.

Fb validate billing address

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/BillingAddress.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/Customer.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/InitialSignUpControllerStep1.java

Ich habe es jetzt implementiert und die Klasse "Billing Address" wieder Rückbenannt zu Customer, damit es hoffentlich keine Merge Conflicts gibt. Schreibt mir gerne wenn ich noch etwas anpassen muss.

Implement logic for billing address

---

Code/bad_walden_stadtwerke/src/main/resources/Bundle_de.properties
Code/bad_walden_stadtwerke/src/main/resources/Bundle_en.properties

Updated error messages and titles in the sign-up process for better clarity
and user experience. Also added a new pop-up title for first-time registration
and adjusted the main application title.

feat: Update sign up error messages and titles

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/MainApplication.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/Language.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/LanguageController.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/SignUpManager.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/LanguageControllerTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/SignUpManagerTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/communication/StandardOutboundRequestHandlerTest.java

added more unit tests for old functionally.
also added some language listeners to adjust titles

fb_added-unit-tests

---

Code/bad_walden_stadtwerke/src/main/resources/Bundle_de.properties
Code/bad_walden_stadtwerke/src/main/resources/Bundle_en.properties

Removed an empty line in the English properties file and updated the German
properties file with the corresponding changes to maintain consistency.
fix for @sternlis request

feat: Removed empty line in English properties file and updated German properties file

---

Code/bad_walden_stadtwerke/dependency-reduced-pom.xml

Adjusted dependency-reduced-pom.xml for actual  project

fix dependency-reduced-pom.xml

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/communication/BadWJsonParser.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/communication/StandardOutboundRequestHandler.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/BillingAddress.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/mock/MockActiveSession.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/mock/MockHttpClient.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/sales/types/Tariff.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/SignUpManager.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/InitialSignUpControllerStep0.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/mainApplication/MainApplicationController.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/communication/StandardOutboundRequestHandlerTest.java

* add tariff selection outbound request
* some refactoring
* some new mock linkage

Web Request improvements

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/InitialSignUpControllerStep0.java

SignupWelcomeText2 was not translated because it was missing in the controller.

Fixed: SignupWelcomeText2 was not Translated.

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/BillingAddress.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/logic/BillingAddressValidator.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/BillingAddressValidatorTest.java

Added Sonderzeichen handling, created Unit Tests.
Added that spaces are trimmed before and after input string.
Fixed issues 30/30 Test pass successfully.

Sonderzeichen handling billing address

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/TariffDisplay.java

Update the display of tariff unit to show "ct /" before the unit in
order to provide clearer information to the user.
solves #61

feat: Update display of tariff unit in TariffDisplay

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/ui/controller/initialSignUp/InitialSignUpControllerStep0.java

Changed method parameter from "electricity" to "water" in the displayTariffs
method to correctly fetch and display water tariffs.

fix: Correct method parameter in InitialSignUpControllerStep0

---

Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/components/errorHandling/ExceptionPopupTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/controller/language/LanguageControllerTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/model/communication/StandardOutboundRequestHandlerTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/model/initialSignUp/SignUpManagerTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/model/types/billingAdress/BillingAddressValidatorTest.java

added unit test linkage of all test classes
solves #87

test: add unit test linkage

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep0.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep1.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep2.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep3.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep4.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/mock/MockHttpClient.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/model/communication/StandardOutboundRequestHandler.java

This solves #92 and makes #77 obsolete
This PR resolves the issue where the program continues to next screen, even if web request is not successful.

Fx continue on faiure issue

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep2.java

Added a call to CentralLoggingUtility.handleException in catch block to improve
error handling in InitialSignUpControllerStep2.

feat: Add central logging utility call in InitialSignUpControllerStep2

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep2.java
Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/controller/initialSignUp/InitialSignUpControllerStep3.java

Refactor code in InitialSignUpControllerStep2 and Step3 to handle null
tariff data more gracefully. Add Platform.runLater() to update UI on
error. Remove unnecessary code for displaying tariffs.

feat: Improve error handling and UI update in signup process

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/utility/CentralLoggingUtility.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/utility/CentralLoggingUtilityTest.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/utility/JsonParserUtilityTest.java

This looked at unit test failure #104 and improves overall unit testing

Fx communication unit test failure

---

Code/bad_walden_stadtwerke/src/main/java/com/bad_walden_stadtwerke/mock/MockHttpClient.java
Code/bad_walden_stadtwerke/src/test/java/com/bad_walden_stadtwerke/model/communication/StandardOutboundRequestHandlerTest.java

Increased the counter for server-side requests and changed error conditions to a list-based approach to improve error simulation in mock server responses.

refactor: Updated mock server-side error handling logic

---

Code/README.md
README.md

Code readme as desired.
Added improved "how to run code" to code readme but also to general readme.

Code readme
